CREATE DATABASE LOJINHA
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE LOJINHA;

CREATE TABLE USUARIOS(
ID_USER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_USER VARCHAR(50) NOT NULL,
EMAIL_USER VARCHAR(60) NOT NULL,
SENHA VARCHAR(32) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
SITUACAO ENUM ('A','B') /*ATICO E BLOQUEADO*/
);

CREATE UNIQUE INDEX IX_USR_1 ON USUARIOS(EMAIL_USER);

CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE FABRICANTES(
ID_FABRICANTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_FABRICANTE VARCHAR(50) NOT NULL
);

CREATE TABLE UNIDADE_FEDERAL(
COD_UF TINYINT NOT NULL PRIMARY KEY,
UF CHAR(2) NOT NULL,
NOME_UF VARCHAR(50) NOT NULL
);

CREATE TABLE CIDADES(
ID_CIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_CIDADE VARCHAR(70) NOT NULL,
COD_MUN CHAR(7) NOT NULL,
COD_UF TINYINT(2) NOT NULL,
FOREIGN KEY(COD_UF) REFERENCES UNIDADE_FEDERAL(COD_UF)
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(100) NOT NULL,
ID_CATEGORIA INT NOT NULL,
ID_FABRICANTE INT NOT NULL,
PRECO_CUSTO DECIMAL(10,2),
PRECO_VENDA DECIMAL(10,2),
PRIMARY KEY(ID_PRODUTO),
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
FOREIGN KEY(ID_FABRICANTE) REFERENCES FABGRICANTES(ID_FABRICANTE) 
);

CREATE TABLE PRODUTO_CARACTER(
ID_PRODUTO INT NOT NULL,
CARACTERISTICA VARCHAR(50) NOT NULL,
VALOR VARCHAR(50) NOT NULL,
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE ESTOQUE(
ID_PRODUTO INT NOT NULL,
ESTOQUE_TOTAL INT NOT NULL,
ESTOQUE_LIVRE INT,
ESTOQUE_RESERVADO INT,
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE CLIENTES(
ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(32) NOT NULL,
SOBRENOME VARCHAR(32) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
SENHA VARCHAR(32) NOT NULL,
DATA_NASC DATETIME NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
ULT_ACESSO DATETIME,
ULT_COMPRA DATETIME,
SITUACAO ENUM('A','B') NOT NULL /*ATIVO E BLOQUEADO*/
);

CREATE TABLE CLIENTE_ENDERECO(
ID_ENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
TIPO ENUM('P','A') NOT NULL, /*PRINCIPAL E ALTERNATIVO*/
ENDERECO VARCHAR(60) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CEP VARCHAR(8) NOT NULL,
ID_CIDADE INT NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY(ID_CIDADE) REFERENCES CIDADES(ID_CIDADE)
);

CREATE TABLE COND_PGTO(
ID_PGTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(50) NOT NULL,
TIPO ENUM('C','D','B') NOT NULL /*CARTÃO, DÉBITO OU BOLETO*/
);

CREATE TABLE COND_PGTO_DET(
ID_PGTO INT NOT NULL,
PARCELA INT NOT NULL,
PERCENTUAL DECIMAL(10,2) NOT NULL,
DIAS INT NOT NULL,
FOREIGN KEY(ID_PGTO) REFERENCES COND_PGTO(ID_PGTO)
);

CREATE TABLE PEDIDOS(
NUM_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
ID_ENDERECO INT NOT NULL,
ID_PGTO INT NOT NULL,
TOTAL_PROD DECIMAL(10,2),
TOTAL_FRETE DECIMAL(10,2),
TOTAL_DESC DECIMAL(10,2),
TOTAL_PEDIDO DECIMAL(10,2),
DATA_PEDIDO DATETIME NOT NULL,
PREVISAO_ENTREGA DATE,
EFETIVA_ENTREGA DATE,
STATUS_PED ENUM('A','S','F','T','E'),
/*AGUARDANDO APROVAÇÃO, SEPARAÇÃO, FATURADO, EM TRANSITO E ENTREGUE*/
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY(ID_ENDERECO) REFERENCES CLIENTE_ENDERECO(ID_ENDERECO),
FOREIGN KEY(ID_PGTO) REFERENCES COND_PGTO(ID_PGTO)
);

CREATE TABLE PEDIDO_ITENS(
NUM_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QTDE INT NOT NULL,
VAL_UNIT DECIMAL(10,2) NOT NULL,
DESCONTO DECIMAL(10,2) NOT NULL,
TOTAL DECIMAL(10,2),
FOREIGN KEY(NUM_PEDIDO) REFERENCES PEDIDOS(NUM_PEDIDO),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE PEDIDO_OBS(
NUM_PEDIDO INT NOT NULL,
OBS VARCHAR(255),
FOREIGN KEY(NUM_PEDIDO) REFERENCES PEDIDOS(NUM_PEDIDO)
);

CREATE TABLE NOTA_FISCAL(
NUM_NOTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NUM_PED_REF INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_ENDERECO INT NOT NULL,
ID_PGTO INT NOT NULL,
TOTAL_PROD DECIMAL(10,2),
TOTAL_FRETE DECIMAL(10,2),
TOTAL_DESC DECIMAL(10,2),
TOTAL_NF DECIMAL(10,2),
DATA_NF DATETIME NOT NULL,
STATUS_NF ENUM('N','C','D'), /*NORMAL, CANCELADA E DEVOLVIDA*/
ID_USER VARCHAR(50),
FOREIGN KEY(NUM_PED_REF) REFERENCES PEDIDOS(NUM_PEDIDO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY(ID_ENDERECO) REFERENCES CLIENTE_ESDERECO(ID_ENDERECO),
FOREIGN KEY(ID_PGTO) REFERENCES COND_PGTO(ID_PGTO)
/*FOREIGN KEY(ID_USER) REFERENCES USUARIOS(ID_USER)*/
);

CREATE TABLE NF_ITENS(
NUM_NOTA INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QTDE INT NOT NULL,
VAL_UNIT DECIMAL(10,2) NOT NULL,
DESCONTO DECIMAL(10,2) NOT NULL,
TOTAL DECIMAL(10,2) NOT NULL,
FOREIGN KEY(NUM_NOTA) REFERENCES NOTA_FISCAL(NUM_NOTA),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE NF_OBS(
NUM_NOTA INT NOT NULL,
OBS VARCHAR(255) NOT NULL,
FOREIGN KEY(NUM_NOTA) REFERENCES NOTA_FISCAL(NUM_NOTA)
);

CREATE TABLE CARRINHO_COMPRAS(
SESSAO VARCHAR(32) NOT NULL,
ID_PRODUTO INT NOT NULL,
QTDE INT NOT NULL,
VAL_UNIT DECIMAL(10,2) NOT NULL,
DESCONTO DECIMAL(10,2) NOT NULL,
TOTAL DECIMAL(10,2) NOT NULL,
DATA_HORA_SESSA DATETIME NOT NULL,
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE INDEX IX_CC_1 ON CARRINHO_COMPRAS(SESSAO);

CREATE TABLE RASTREABILIDADE(
NUM_PEDIDO INT NOT NULL,
STATUS_PED CHAR(1) NOT NULL,
DATA_HORA DATETIME NOT NULL,
ID_USER VARCHAR(50),
FOREIGN KEY(NUM_PEDIDO) REFERENCES PEDIDO(NUM_PEDIDO)
);